name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: khlopko/setup-swift@8c5838998011c82263d88bb41987a43d9ade7363
        with:
          swift-version: "6.0-snapshot"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: swift build
      - name: Test
        run: swift test
      - name: Run
        run: swift run
